### ISSUE TITLE
 Compiled binary CD ISO request

### ISSUE THREAD

**Issue by s-mohammad-dabir** [mvardan/ros-svn-mirror#1]
Hi,
Thank you for your fixes.Would you please release a compiled binary CD image of this project?

**Comment by mvardan** [comment]
Hi,
The repo on which you opened this issue isn't containing any of my commits, this is just mirror of ReactOS SVN repository. You can download CD image for any of revisions from here (https://reactos.org/getbuilds/).

Thanks,
Vardan.
